### ISSUE TITLE
Embroider + AuDropdown: Can't module not found focus-trap

### ISSUE THREAD

**Issue by snenenenenenene** [appuniversum/ember-appuniversum#355]
When adding the **AuDropdown** component to an **Embroider** project it returns:

` modifiers/focus-trap.js: Module not found: Error: Can't resolve '/Users/torwynd/Developer/lynx/node_modules/ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/e0c590/modifiers/focus-trap.js'
        at PackagerRunner (@embroider/webpack)`

**To Reproduce**
1. Add Embroider to Ember project.
2. Add `<AuDropdown @title='Aangemeld als ...' @alignment='right'>` to the application.hbs file for instance.
3. Curse at your screen for opening the Pandora's box that is Embroider.

**Expected behavior**
A functional Dropdown component

**Full stack trace**
`
                ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/torwynd/Developer/lynx/node_modules/ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/e0c590/modifiers/focus-trap.js'
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/torwynd/Developer/lynx/node_modules/neo-async/async.js:6883:13
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
              
                    at new Plugin (/Users/torwynd/Developer/lynx/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new PackagerRunner (/Users/torwynd/Developer/lynx/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
    at Object.defaultPipeline (/Users/torwynd/Developer/lynx/node_modules/@embroider/compat/src/default-pipeline.js:49:12)
    at module.exports (/Users/torwynd/Developer/lynx/ember-cli-build.js:54:39)
    at Builder.readBuildFile (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/builder.js:48:20)
    at async Builder.setupBroccoliBuilder (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/builder.js:68:17)
    at async Builder.ensureBroccoliBuilder (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/builder.js:56:7)
    at async Watcher.constructBroccoliWatcher (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/watcher.js:59:5)
    at async Watcher.setupBroccoliWatcher (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/watcher.js:43:37)
    at async Function.build (/Users/torwynd/Developer/lynx/node_modules/ember-cli/lib/models/watcher.js:31:5)
              
                ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/torwynd/Developer/lynx/node_modules/ember-focus-trap/modifiers/focus-trap.js' in '$TMPDIR/embroider/e0c590/modifiers/focus-trap.js'
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/torwynd/Developer/lynx/node_modules/neo-async/async.js:6883:13
    at /Users/torwynd/Developer/lynx/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/torwynd/Developer/lynx/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
`

**Desktop:**
 - OS: MacOS Ventura [ARM]
 - Browser Chrome
 - Version 107

**Comment by Windvis** [comment]
I think this is the underlying Embroider issue: https://github.com/embroider-build/embroider/issues/1175

This was supposedly fixed, but it might not be according to the last comment in the thread. Which version of Embroider did you use?

**Comment by Windvis** [comment]
We're using Embroider in a couple of apps now and this error doesn't trigger anymore, so we can close this.
